- client/client.go
- client/reactor_test.go
> client: remove extraneous `ParseDuration` call

- .gitignore
- .travis.gofmt.sh
- .travis.yml
- Makefile
- ircmsg/message.go
Right now, we copy the message a lot of times:
1. Incrementally, to build it from immutable `string` objects
1. Into a `[]byte` so it can be sent
1. Into another string for logging (because we have to chop off the `\r\n`), whether or not the line will actually be logged
Anyway, if we build it using `bytes.Buffer`, then `buffer.Bytes()` gives us access to the same underlying array that was used for building. Total savings is up to 25% on some microbenchmarks (requiring accompanying changes to oragono).
> build IRCMessage using bytes.Buffer

- .check-gofmt.sh
- Makefile
- client/reactor_test.go
- ircfmt/ircfmt_test.go
- ircmsg/message.go
- ircmsg/message_test.go
- ircmsg/tags.go
- ircmsg/tags_test.go
1. `ircmsg/message.go` and `ircmsg/tags.go` have been completely rewritten, basically; it's probably easier to read them directly than to look at the diffs
1. `IrcMessage` no longer directly exposes a `Tags` member, instead exposing getters and setters. This is so we can internally separate client-only tags. (We can also optimize out initialization of the map, which involves dynamic allocation, in the case where there are no tags. Down the line, I'm thinking about the possibility of adding a `[4]string` that stores the most commonly occurring tags without needing a dynamic allocation; that's probably unnecessary though.)
1. The interfaces have gotten more...awkward. The generation interfaces are `Line(fromClient bool, truncateLen int)` and `LineBytes(fromClient bool, truncateLen int)`. …
> ircmsg: support ratified message-tags spec

- ircfmt/ircfmt.go
- ircfmt/ircfmt_test.go
when escaping a string such as `test $c`, it is incorrectly escaped to `test $c[]`, which, if unescaped, becomes `test \x03`. This PR fixes this issue, and adds an additional test to confirm that the escaping is stable when chained.
> fix $c being incorrectly escaped

- client/actions.go
- client/client.go
- client/reactor_test.go
As the title implies this fixes the broken example client that comes with the library. Now I'm not 100% sure if tags work fully however in my limited testing everything appears in order.
Cheers.
> Update the Example IRC-Go Client to Function with the New Tag Handling System

- client/client.go
>%!E(MISSING). %!E(MISSING) everywhere.
Fprintf spews out garbarge when you throw in a percent sign with no formatters specificed. This fixes that problem.
> Correct incorrect usage of fmt.Fprintf

- client/client.go
This adds a basic command handler to the example client. To use this, register an event starting with `cmd` followed by the prefix (`!`, `@`, `$`, `~`, `.`) and the command trigger word.
As an example on how it's used:
`server.RegisterEvent("in", "cmd!quit", quitHandler, 0)` would execute `quitHandler` when it receives a PRIVMSG containing `!quit`
> Basic Command Handler

- client/client.go
As the title implies this adds an additional (more sane) set of args starting after the command to the infomap emitted by commands. It may need some additional formatting so it looks nicer.
> [WIP] Add an additional array of arguments to the simple command event infomap

- Makefile
- go.mod
- go.sum
- ircmsg/message.go
- ircmsg/message_test.go
The rationale is that we're never going to be rid of forced trailing parameters, they're too entrenched. So using this library in practice is always going to require some kind of workaround, and it's much cleaner to provide it here than to do the thing Oragono currently does.
> switch to modules, add ForceTrailing to ircmsg

- go.mod
- go.sum
`go get github.com/goshuirc/irc-go` is adding e-nfa to Oragono's go.mod, for reasons I don't entirely understand --- but this might fix it?
> run `go mod tidy`

- .travis.yml
- Makefile
- ircmsg/tags.go
- ircmsg/tags_test.go
Not a huge deal. Speeds up the slowpath where we actually have to process escapes by a tiny amount.
> use strings.Builder for tag unescaping

- ircreader/ircreader.go
For parity with (*bufio.Reader).ReadLine(), which does the same
> IRCReader: trim \r if the line ending was \r\n

- ircutils/unicode.go
- ircutils/unicode_test.go
Duplicates some logic present in ircmsg, but whatever.
> add UTF8-safe truncation utility function

- ircevent/README.markdown
- ircmsg/message.go
- ircmsg/message_test.go
I'm envisioning this as the last major API break, after which we will tag v0.1.0 with the intention of maintaining backwards compatibility. If we successfully keep to that intention we will subsequently tag v1.0.0.
> rename Message.Prefix to Source

- ircevent/irc.go
- ircevent/irc_labeledresponse_test.go
cc @progval.
I was working on the client-side implementation of https://github.com/ergochat/ergo/issues/1593 and realized that what we really want is a synchronous API for labeled-response: block until the response is available.
Right now a timeout guarantee is implicit in the labeled-response logic: a response that doesn't arrive within `2 * (*Connection).Timeout` will be cleaned up and the callback invoked with `nil`, triggering an error response. But maybe this method should take its own timeout argument?
> ircevent: add synchronous GetLabeledResponse API

- ircfmt/ircfmt.go
- ircfmt/ircfmt_test.go
The style for this library is not to use IRC as a naming prefix: compare 23a3bb8f66e6a7.
> rename ircfmt.IRCColor to ColorCode

- ircmsg/message.go
- ircmsg/unicode.go
- ircmsg/unicode_test.go
- ircutils/unicode.go
- ircutils/unicode_test.go
A message that exceeds the length limit is a protocol violation, so handling is implementation-defined and it's not really a correctness issue for us to truncate it additionally.
Also move TruncateUTF8Safe into ircmsg (providing an alias in ircutils for API compatibility).
> ircmsg: UTF8-aware truncation during parsing

- ircmsg/message_test.go
This covers the behavior in #94 directly in the tests for `ircmsg.ParseLineStrict`.
> test utf8-aware truncation in ircmsg

- ircevent/irc.go
In https://github.com/autobrr/autobrr/pull/1239 we would like to check if the error returned is a `clientHasQuit` error and handle it differently if so.
> expose clientHasQuit error

- ircevent/irc_struct.go
- ircevent/irc_test.go
> add GetReplyTarget

- ircmsg/message.go
- ircmsg/message_test.go
> ircmsg: validate that commands are ASCII
